# Generated by Django 3.0 on 2020-09-23 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200920_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='in_reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.Post'),
        ),
    ]
