# Generated by Django 3.0 on 2021-01-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200926_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
